SuppliersProducts/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuppliersProducts.Data;
using SuppliersProducts.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using SuppliersProducts.ViewModel;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using System.Runtime.InteropServices.ComTypes;

namespace SuppliersProducts.Controllers
{
    public class FilesController : Controller
    {
        private readonly DataBaseContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        public FilesController(DataBaseContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Files
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.File.ToListAsync());
        }

        // GET: Files/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.File
                .FirstOrDefaultAsync(m => m.ID == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // GET: Files/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Files/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,file")] FileView model, IFormFile file)
        {
            /*var dir = _hostingEnvironment.ContentRootPath;

            using (var fileStream=new FileStream(Path.Combine(dir,file.FileName),FileMode))*/
            if (file != null)
            {

                string path = _hostingEnvironment.ContentRootPath +"\\"+ file.FileName;

                using (var fileStream = new System.IO.FileStream(path, System.IO.FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                model.file.CopyTo(new System.IO.FileStream(path, System.IO.FileMode.Create));
                ViewModel.File newFile = new ViewModel.File
                {
                    filePath = path
                };
                _context.Add(newFile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View();
        }
        // GET: Files/Edit/5
        public IActionResult Compare()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Compare(string fp1,string fp2)
        {
            Plagiator test = new Plagiator();
            double comparator = test.AveragePlagTest(fp1, fp2);

            return Content(comparator.ToString());
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,filePath")] ViewModel.File file)
        {
            if (id != file.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(file);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FileExists(file.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(file);
        }

        // GET: Files/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var file = await _context.File
                .FirstOrDefaultAsync(m => m.ID == id);
            if (file == null)
            {
                return NotFound();
            }

            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var file = await _context.File.FindAsync(id);
            _context.File.Remove(file);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FileExists(int id)
        {
            return _context.File.Any(e => e.ID == id);
        }
    }
}

SuppliersProducts/Views/Files/Compare.cshtml
@{
    ViewData["Title"] = "Compare";
}

<h1>Compare</h1>
<form method="post">
    <label>String1</label><br />
    <input type="text" name="fp1" /><br /><br />
    <label>String2</label><br />
    <input type="text" name="fp2" /><br /><br />
    <input type="submit" value="Go!" />
</form>

SuppliersProducts/Views/Files/Create.cshtml
@model SuppliersProducts.ViewModel.FileView

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>File</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="custom-file"></div>
            <div class="form-group">
                <input asp-for="file" class="form-control custom-file-input">
                <label asp-for="file" class="custom-file-label">Choose File...</label>
            </div>
            <div class="form-group">
                <input type="submit" name="btn_create"value="Create" class="btn btn-primary" />
                <button name="compare" asp-action="Compare">Compare</button>
            </div>

            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });

                </script>

            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SuppliersProducts/Views/Files/Index.cshtml
@model IEnumerable<SuppliersProducts.ViewModel.File>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.filePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.filePath)
                </td>

                <td>
                    <a asp-controller="Files" asp-action="Compare">Compare</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>