SuppliersProducts/Controllers/LabWorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuppliersProducts.Data;
using SuppliersProducts.Models;

namespace SuppliersProducts.Controllers
{
    public class LabWorksController : Controller
    {
        private readonly DataBaseContext _context;

        public LabWorksController(DataBaseContext context)
        {
            _context = context;
        }

        // GET: Products
        [Authorize]
        public async Task<IActionResult> Index(string sortOrder, string searchStringName, string searchStringType)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TypeSortParm"] = sortOrder == "Type" ? "type_desc" : "Type";

            var labwork = from s in _context.LabWorks
                           select s;
            if (!String.IsNullOrEmpty(searchStringName))
            {
                labwork = labwork.Where(s => s.Name.Contains(searchStringName));
                ViewData["CurrentNameFilter"] = searchStringName;
            }
            if (!String.IsNullOrEmpty(searchStringType))
            {
                labwork = labwork.Where(s => s.Type.Contains(searchStringType));
                ViewData["CurrentTypeFilter"] = searchStringType;
            }
            switch (sortOrder)
            {
                case "name_desc":
                    labwork = labwork.OrderByDescending(s => s.Name);
                    break;
                case "Type":
                    labwork = labwork.OrderByDescending(s => s.Type);
                    break;
                case "type_desc":
                    labwork = labwork.OrderBy(s => s.Type);
                    break;
                default:
                    labwork = labwork.OrderBy(s => s.Name);
                    break;
            }

            return View(await labwork.AsNoTracking().ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labwork = await _context.LabWorks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (labwork == null)
            {
                return NotFound();
            }

            return View(labwork);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Type")] LabWork product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labwork = await _context.LabWorks.FindAsync(id);
            if (labwork == null)
            {
                return NotFound();
            }
            return View(labwork);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Type")] LabWork labwork)
        {
            if (id != labwork.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(labwork);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LabWorkExists(labwork.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(labwork);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var labwork = await _context.LabWorks
                .FirstOrDefaultAsync(m => m.ID == id);
            if (labwork == null)
            {
                return NotFound();
            }

            return View(labwork);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.LabWorks.FindAsync(id);
            _context.LabWorks.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LabWorkExists(int id)
        {
            return _context.LabWorks.Any(e => e.ID == id);
        }
    }
}

SuppliersProducts/Controllers/PassingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuppliersProducts.Data;
using SuppliersProducts.Models;

namespace SuppliersProducts.Controllers
{
    public class PassingsController : Controller
    {
        private readonly DataBaseContext _context;

        public PassingsController(DataBaseContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index(string sortOrder, string searchStringName, DateTime searchStringDate, string searchStringPlace)
        {
            var dataBaseContext = _context.Passings.Include(o => o.Teacher).Include(o => o.LabWork);

            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["PlaceSortParm"] = sortOrder == "Place" ? "place_desc" : "Place";
            ViewData["LabWorkSortParm"] = sortOrder == "LabWork" ? "labwork_desc" : "LabWork";
            ViewData["TeacherSortParm"] = sortOrder == "Teacher" ? "teacher_desc" : "teacher";


            var passing = from s in dataBaseContext
                               select s;

            if (!String.IsNullOrEmpty(searchStringName))
            {
                passing = passing.Where(s => s.Name.Contains(searchStringName));
                ViewData["CurrentNameFilter"] = searchStringName;
            }
            if (searchStringDate != null && searchStringDate != DateTime.Parse("1/1/0001 12:00:00 AM"))
            {
                passing = passing.Where(s => s.Date.Equals(searchStringDate));
                ViewData["CurrentDateFilter"] = searchStringDate.ToShortDateString();
            }
            if (!String.IsNullOrEmpty(searchStringPlace))
            {
                passing = passing.Where(s => s.Place.Contains(searchStringPlace));
                ViewData["CurrentPlaceFilter"] = searchStringPlace;
            }

            switch (sortOrder)
            {
                case "name_desc":
                    passing = passing.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    passing = passing.OrderBy(s => s.Date);
                    break;
                case "date_desc":
                    passing = passing.OrderByDescending(s => s.Date);
                    break;
                case "Place":
                    passing = passing.OrderBy(s => s.Place);
                    break;
                case "place_desc":
                    passing = passing.OrderByDescending(s => s.Place);
                    break;
                case "LabWork":
                    passing = passing.OrderBy(s => s.LabWork.Name);
                    break;
                case "labwork_desc":
                    passing = passing.OrderByDescending(s => s.LabWork.Name);
                    break;
                case "Teacher":
                    passing = passing.OrderBy(s => s.Teacher.FullName);
                    break;
                case "teacher_desc":
                    passing = passing.OrderByDescending(s => s.Teacher.FullName);
                    break;

                default:
                    passing = passing.OrderBy(s => s.Name);
                    break;
            }


            return View(await passing.AsNoTracking().ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Passings
                .Include(o => o.Teacher)
                .Include(o => o.LabWork)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["TeacherID"] = new SelectList(_context.Teachers, "ID", "Address");
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,LabWorkID,TeacherID,Name,Date,Place")] Passing passing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeacherID"] = new SelectList(_context.Teachers, "ID", "Address", passing.TeacherID);
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", passing.LabWorkID);
            return View(passing);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passing = await _context.Passings.FindAsync(id);
            if (passing == null)
            {
                return NotFound();
            }
            ViewData["TeacherID"] = new SelectList(_context.Teachers, "ID", "Address", passing.TeacherID);
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", passing.LabWorkID);
            return View(passing);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,LabWorkID,TeacherID,Name,Date,Place")] Passing passing)
        {
            if (id != passing.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassingExists(passing.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeacherID"] = new SelectList(_context.Teachers, "ID", "Address", passing.TeacherID);
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", passing.LabWorkID);
            return View(passing);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passing = await _context.Passings
                .Include(o => o.Teacher)
                .Include(o => o.LabWork)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (passing == null)
            {
                return NotFound();
            }

            return View(passing);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passing = await _context.Passings.FindAsync(id);
            _context.Passings.Remove(passing);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassingExists(int id)
        {
            return _context.Passings.Any(e => e.ID == id);
        }
    }
}

SuppliersProducts/Views/Shared/Coarusel.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">
        
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="~/img/1.jpg"  style="width:100%;">
                </div>

                <div class="item">
                    <img src="~/img/3.jpg" style="width:100%;">
                </div>

                <div class="item">
                    <img src="~/img/4.jpg"  style="width:100%;">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

</body>
</html>

SuppliersProducts/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" >
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-link text-dark" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a class="nav-link text-dark" id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a class="nav-link text-dark" id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

SuppliersProducts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuppliersProducts</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LabWorks" asp-action="Index">LabWorks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentLabWorks" asp-action="Index">StudentLabWorks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passings" asp-action="Index">Passings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>



                    </ul>
                    @await Html.PartialAsync("LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CourseProject<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>