SuppliersProducts/Models/StudentLabWork.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuppliersProducts.Models
{
    public class StudentLabWork
    {
        public int ID { get; set; }

        [Display(Name = "LabWork")]
        public int LabWorkID { get; set; }
        [Display(Name = "Student")]
        public int StudentID { get; set; }

        public LabWork LabWork { get; set; }
        public Student Student { get; set; }

    }
}

SuppliersProducts/Controllers/StudentLabWorksController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SuppliersProducts.Data;
using SuppliersProducts.Models;
using SuppliersProducts.ViewModel;

namespace SuppliersProducts.Controllers
{
    public class StudentLabWorksController : Controller
    {
        private readonly DataBaseContext _context;
        IHostingEnvironment _hostingEnvironment;

        public StudentLabWorksController(DataBaseContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: SupplierProducts
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var dataBaseContext = _context.StudentLabWork.Include(s => s.LabWork).Include(s => s.Student);
            return View(await dataBaseContext.ToListAsync());
        }

        // GET: SupplierProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLabWork = await _context.StudentLabWork
                .Include(s => s.LabWork)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (studentLabWork == null)
            {
                return NotFound();
            }

            return View(studentLabWork);
        }

        // GET: SupplierProducts/Create
        public IActionResult Create()
        {
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name");
            ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName");
            ViewData["Path"] = new SelectList(_context.StudentLabWork, "ID", "Path");
            return View();
        }

        // POST: SupplierProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,LabWorkID,StudentID,Path")] SLabView sLabView, IFormFile Path)
        {
            /* if (file != null)
                        {

                            string path = _hostingEnvironment.ContentRootPath +"\\"+ file.FileName;

                            using (var fileStream = new System.IO.FileStream(path, System.IO.FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }
                            model.file.CopyTo(new System.IO.FileStream(path, System.IO.FileMode.Create));
                            ViewModel.File newFile = new ViewModel.File
                            {
                                filePath = path
                            };
                            _context.Add(newFile);
                            await _context.SaveChangesAsync();
                            return RedirectToAction(nameof(Index));

                        }*/

            if (ModelState.IsValid)
            {
                if(Path!=null)
                {
                    string path = _hostingEnvironment.ContentRootPath + "\\" + Path.FileName;
                    using (var fileStream = new System.IO.FileStream(path, System.IO.FileMode.Create))
                    {
                        await Path.CopyToAsync(fileStream);
                    }
                    sLabView.Path.CopyTo(new System.IO.FileStream(path, System.IO.FileMode.Create));
                    StudentLabWork studentLabWork = new StudentLabWork
                    {
                        StudentID = sLabView.StudentID,
                        LabWorkID = sLabView.LabWorkID,
                        Path = Path.FileName

                    };
                    _context.Add(studentLabWork);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", sLabView.LabWorkID);
                ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName", sLabView.StudentID);
                //ViewData["Path"] = new SelectList(_context.StudentLabWork, "ID", "Path", sLabView.Path);

            }

            return View();
        }
        // GET: SupplierProducts/Compare/5
        public IActionResult Compare()
        {
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name");
            ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName");
            ViewData["Path"] = new SelectList(_context.StudentLabWork, "ID", "Path");
            return View();
        }
        [HttpPost, ActionName("Compare")]
        public async Task<IActionResult> Compare([Bind("ID,StudentID,Path")] StudentLabWork studentLab, int fp1, int fp2,
            Student student, LabWork labwork)
        {
            string res = null;


            var studentLabWork1 = await _context.StudentLabWork.FindAsync(fp1);
            int idstudent1 = studentLabWork1.StudentID;
            var dbstudent1 = await _context.Student.FindAsync(idstudent1);
            string student1 = dbstudent1.FullName;
            int idlab1 = studentLabWork1.StudentID;
            var dblab1 = await _context.LabWorks.FindAsync(idlab1);
            string lab1 = dblab1.Name;

            string f1 = _hostingEnvironment.ContentRootPath + "\\" + studentLabWork1.Path;

            var studentLabWork2 = await _context.StudentLabWork.FindAsync(fp2);
            string f2 = _hostingEnvironment.ContentRootPath + "\\" + studentLabWork2.Path;
            int idstudent2 = studentLabWork2.StudentID;
            var dbstudent2 = await _context.Student.FindAsync(idstudent2);
            string student2 = dbstudent2.FullName;
            int idlab2 = studentLabWork2.StudentID;
            var dblab2 = await _context.LabWorks.FindAsync(idlab1);
            string lab2 = dblab1.Name;
            Plagiator test = new Plagiator();
               double comparator = test.AveragePlagTest(f1, f2);
            comparator = comparator * 100;
            @ViewBag.lab1 = lab1;
            @ViewBag.lab2 = lab2;
            @ViewBag.student1 = student1;
            @ViewBag.student2 = student2;

            @ViewBag.Result = comparator.ToString()+"%";
           ViewBag.UltimateRes=" Lab "+ @ViewBag.lab1+ " of " + @ViewBag.student1 + " and lab " + @ViewBag.lab2 + " of " + @ViewBag.student2 +
              " has " + @ViewBag.Result + " of plagiat code.";
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name");
            ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName");
            ViewData["Path"] = new SelectList(_context.StudentLabWork, "ID", "Path");
            return View();
            

           
           
        }

            // GET: SupplierProducts/Edit/5
            public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLabWork = await _context.StudentLabWork.FindAsync(id);
            if (studentLabWork == null)
            {
                return NotFound();
            }
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", studentLabWork.LabWorkID);
            ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName", studentLabWork.StudentID);
            return View(studentLabWork);
        }

        // POST: SupplierProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,LabWorkID,StudentID")] StudentLabWork studentLabWork)
        {
            if (id != studentLabWork.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentLabWork);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentLabWorkExists(studentLabWork.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LabWorkID"] = new SelectList(_context.LabWorks, "ID", "Name", studentLabWork.LabWorkID);
            ViewData["StudentID"] = new SelectList(_context.Student, "ID", "FullName", studentLabWork.StudentID);
            return View(studentLabWork);
        }

        // GET: SupplierProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentLabWork = await _context.StudentLabWork
                .Include(s => s.LabWork)
                .Include(s => s.Student)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (studentLabWork == null)
            {
                return NotFound();
            }

SuppliersProducts/Views/StudentLabWorks/Compare.cshtml
@model SuppliersProducts.Models.StudentLabWork
@{
    ViewData["Title"] = "Compare";
}

<h1>Compare</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Compare" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <select name="fp1" asp-for="Path" class="form-control" asp-items="ViewBag.Path"></select>
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <select name="fp2" asp-for="Path" class="form-control" asp-items="ViewBag.Path"></select>
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div>
               @ViewBag.UltimateRes
            </div>
            <div class="form-group">
                <input type="submit" value="Compare" class="btn btn-primary" />
            </div>
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

SuppliersProducts/Views/StudentLabWorks/Create.cshtml
@model SuppliersProducts.Models.StudentLabWork

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentLabWork</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LabWorkID" class="control-label"></label>
                <select asp-for="LabWorkID" class ="form-control" asp-items="ViewBag.LabWorkID"></select>
            </div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <select asp-for="StudentID" class ="form-control" asp-items="ViewBag.StudentID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuppliersProducts/Views/StudentLabWorks/Delete.cshtml
@model SuppliersProducts.Models.StudentLabWork

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SupplierProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LabWork)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LabWork.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FullName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuppliersProducts/Views/StudentLabWorks/Details.cshtml
@model SuppliersProducts.Models.StudentLabWork

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SupplierProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LabWork)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LabWork.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuppliersProducts/Views/StudentLabWorks/Edit.cshtml
@model SuppliersProducts.Models.StudentLabWork

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentLabWorks</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="LabWorkID" class="control-label"></label>
                <select asp-for="LabWorkID" class="form-control" asp-items="ViewBag.LabWorkID"></select>
                <span asp-validation-for="LabWorkID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <select asp-for="StudentID" class="form-control" asp-items="ViewBag.StudentID"></select>
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuppliersProducts/Views/StudentLabWorks/Index.cshtml
@model IEnumerable<SuppliersProducts.Models.StudentLabWork>

@{
    ViewData["Title"] = "Index";
}

<h1>StudLabsWorks</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LabWork)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(item=>item.Path)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LabWork.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Path)
            </td>
            <td>
                <a asp-action="Compare" asp-controller="StudentLabWorks">Compare</a> |
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>